export const SELECT_TRIGGER = "SELECT_TRIGGER";
export const DISSELECT_TRIGGER = "DISSELECT_TRIGGER";

export const OPEN_ACTION_MODAL = "OPEN_ACTION_MODAL";
export const CLOSE_ACTION_MODAL = "CLOSE_ACTION_MODAL";

export const OPEN_VERSION_HISTORY = "OPEN_VERSION_HISTORY";
export const CLOSE_VERSION_HISTORY = "CLOSE_VERSION_HISTORY";

export const OPEN_TRIGGER_SIDEBAR = "OPEN_TRIGGER_SIDEBAR";
export const CLOSE_TRIGGER_SIDEBAR = "CLOSE_TRIGGER_SIDEBAR";

export const OPEN_ACTION_SIDEBAR = "OPEN_ACTION_SIDEBAR";
export const CLOSE_ACTION_SIDEBAR = "CLOSE_ACTION_SIDEBAR";

export const OPEN_TEST_MODAL = "OPEN_TEST_MODAL";
export const CLOSE_TEST_MODAL = "CLOSE_TEST_MODAL";

export const ADD_TRIGGER_BEGIN = "ADD_TRIGGER_BEGIN";
export const ADD_TRIGGER_SUCCESS = "ADD_TRIGGER_SUCCESS";
export const ADD_TRIGGER_ERROR = "ADD_TRIGGER_ERROR";

export const ADD_NULL_TO_TRIGGER = "ADD_NULL_TO_TRIGGER";

export const ADD_NULL_TO_ACTION = "ADD_NULL_TO_ACTION";
export const APPEND_NULL_TO_ACTION = "APPEND_NULL_TO_ACTION";

export const ADD_ACTION_BEGIN = "ADD_ACTION_BEGIN";
export const ADD_ACTION_SUCCESS = "ADD_ACTION_SUCCESS";
export const ADD_ACTION_ERROR = "ADD_ACTION_ERROR";

export const ADD_ACTION_BETWEEN = "ADD_ACTION_BETWEEN";

export const SET_DRAGGING_ACTION = "SET_DRAGGING_ACTION";

export const DUPLICATE_TRIGGER_BEGIN = "DUPLICATE_TRIGGER_BEGIN";
export const DUPLICATE_TRIGGER_SUCCESS = "DUPLICATE_TRIGGER_SUCCESS";
export const DUPLICATE_TRIGGER_ERROR = "DUPLICATE_TRIGGER_ERROR";

export const DELETE_TRIGGER_BEGIN = "DELETE_TRIGGER_BEGIN";
export const DELETE_TRIGGER_SUCCESS = "DELETE_TRIGGER_SUCCESS";
export const DELETE_TRIGGER_ERROR = "DELETE_TRIGGER_ERROR";

export const ADD_TRIGGER_BETWEEN = "ADD_TRIGGER_BETWEEN";
export const ADD_ACTION_TOP = "ADD_ACTION_TOP";

export const SET_DRAGGING_TRIGGER = "SET_DRAGGING_TRIGGER";

export const ADD_FIRST_TRIGGER = "ADD_FIRST_TRIGGER";

export const OPEN_DELETE_TRIGGER_MODAL = "OPEN_DELETE_TRIGGER_MODAL";
export const CLOSE_DELETE_TRIGGER_MODAL = "CLOSE_DELETE_TRIGGER_MODAL";

export const SET_TRIGGERS_DATA = "SET_TRIGGERS_DATA";
export const SET_ACTIONS_DATA = "SET_ACTIONS_DATA";

export const SEARCH_TRIGGERS = "SEARCH_TRIGGERS";
export const SEARCH_ACTIONS = "SEARCH_ACTIONS";

export const REMOVE_NULL_FROM_TRIGGER = "REMOVE_NULL_FROM_TRIGGER";

export const SET_TRIGGER_DROP_ACTIVE_TRUE = "SET_TRIGGER_DROP_ACTIVE_TRUE";
export const SET_TRIGGER_DROP_ACTIVE_FALSE = "SET_TRIGGER_DROP_ACTIVE_FALSE";

export const ADD_LAST_TRIGGER = "ADD_LAST_TRIGGER";
export const OPEN_SEARCH_SIDEBAR = "OPEN_SEARCH_SIDEBAR";
export const CLOSE_SEARCH_SIDEBAR = "CLOSE_SEARCH_SIDEBAR";

export const LAST_TRIGGER_ACTIVE_TRUE = "LAST_TRIGGER_ACTIVE_TRUE";
export const LAST_TRIGGER_ACTIVE_FALSE = "LAST_TRIGGER_ACTIVE_FALSE";

export const REMOVE_NULL_FROM_ACTION = "REMOVE_NULL_FROM_ACTION";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const OPEN_LOGIC_TEST = "OPEN_LOGIC_TEST";
export const CLOSE_LOGIC_TEST = "CLOSE_LOGIC_TEST";

export const GET_TRIGGER_BACK = "GET_TRIGGER_BACK";
export const GET_ACTION_BACK = "GET_ACTION_BACK";

export const SET_DETAIL_TAB = "SET_DETAIL_TAB";
export const RUN_SINGLE_TRIGGER_TEST = "RUN_SINGLE_TRIGGER_TEST";

export const MOVE_TRIGGER = "MOVE_TRIGGER";

export const SELECT_TAB = "SELECT_TAB";
export const SET_ITEM_DRAG_ON_CANVAS = "SET_ITEM_DRAG_ON_CANVAS";

export const APPEND_NULL_TO_TRIGGER = "APPEND_NULL_TO_TRIGGER";

export const OPEN_WORKFLOW_DELETE_CONFIRMATION =
  "OPEN_WORKFLOW_DELETE_CONFIRMATION";
export const CLOSE_WORKFLOW_DELETE_CONFIRMATION =
  "CLOSE_WORKFLOW_DELETE_CONFIRMATION";

export const DELETE_WORKFLOW = "DELETE_WORKFLOW";

export const CANVAS_CLICKED = "CANVAS_CLICKED";

export const MOVE_ACTIONS = "MOVE_ACTIONS";

export const SET_ACTIONS_DROP_ACTIVE_TRUE = "SET_ACTIONS_DROP_ACTIVE_TRUE";

export const SET_ACTIONS_DROP_ACTIVE_FALSE = "SET_ACTIONS_DROP_ACTIVE_FALSE";

export const SET_ACTIVE_ACTION_DROP_INDEX = "SET_ACTIVE_ACTION_DROP_INDEX";

export const ADD_NULL_BETWEEN_ACTION = "ADD_NULL_BETWEEN_ACTION";

export const SET_FOCUS_ELEMENT = "SET_FOCUS_ELEMENT";

export const RESTORE_VERSION = "RESTORE_VERSION";
export const SET_EDITING_VERSION = "SET_EDITING_VERSION";
export const OPEN_VERSION_NAME_MODAL = "OPEN_VERSION_NAME_MODAL";
export const CLOSE_VERSION_NAME_MODAL = "CLOSE_VERSION_NAME_MODAL";

export const GET_ALL_EVENTS = "GET_ALL_EVENTS";
export const GET_EVENTS_TRIGGER = "GET_EVENTS_TRIGGER";
export const GET_EVENTS_ACTION = "GET_EVENTS_ACTION";

export const CHANGE_PUBLISH_STATE = "CHANGE_PUBLISH_STATE";

export const RENAME_WORKFLOW = "RENAME_WORKFLOW";

export const SET_EVENT = "SET_EVENT";

export const SAVE_TRIGGER_DATA = "SAVE_TRIGGER_DATA";

export const UPLOAD_TRIGGER_IMAGES = "UPLOAD_TRIGGER_IMAGES";
